# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cache.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\"\x1b\n\x0c\x43\x61\x63heRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\'\n\tCacheData\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\".\n\rCacheResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2e\n\x0c\x43\x61\x63heService\x12+\n\x08GetValue\x12\r.CacheRequest\x1a\x0e.CacheResponse\"\x00\x12(\n\x08SetValue\x12\n.CacheData\x1a\x0e.CacheResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CACHEREQUEST']._serialized_start=15
  _globals['_CACHEREQUEST']._serialized_end=42
  _globals['_CACHEDATA']._serialized_start=44
  _globals['_CACHEDATA']._serialized_end=83
  _globals['_CACHERESPONSE']._serialized_start=85
  _globals['_CACHERESPONSE']._serialized_end=131
  _globals['_CACHESERVICE']._serialized_start=133
  _globals['_CACHESERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
